config/routes.rb
Rails.application.routes.draw do
  
  get 'buscador/index'

  resources :series_temps do
    resources :comentarios
  end
 
  devise_for :users
  resources :categories
  resources :movies do
  resources :comments  
  end  

    root 'series_temps#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :movies
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :season

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :series_temp
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :movie
 
  enum likes: {mala: 0, regular: 1, buena: 2, buenisima: 3 , excelente: 4}
end

app/models/comment_serie.rb
class CommentSerie < ActiveRecord::Base
  belongs_to :series_temp
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many  :comments, dependent: :destroy
  belongs_to :category
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
  before_validation :youtube
   
  def youtube   #este sirve para cambiar el link que se agrega desde youtube, por el embed
    youtube = video.split("=").last   
    self.video = "https://www.youtube.com/embed/" + youtube
  end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :series_temp
  has_many :chapters, dependent: :destroy
  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true

end

app/models/series_temp.rb
class SeriesTemp < ActiveRecord::Base
  has_many :seasons, dependent: :destroy
  accepts_nested_attributes_for :seasons, reject_if: :all_blank, allow_destroy: true
  has_many :comentarios, dependent: :destroy    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/buscador_controller.rb
class BuscadorController < ApplicationController
  def index
  	@q = SeriesTemp.ransack(params[:q])
    @series_temps = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 5).order(name: :asc) 
  	 respond_to do |f|
        f.js
      end  
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments.create(comment_params)
    redirect_to movie_path(@movie)
    
  end
  
  
  def destroy
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments.find(params[:id])
    @comment.destroy
    redirect_to movie_path(@movie)
  end
  
  
 
  private
    def comment_params
      params.require(:comment).permit(:user, :body, :likes)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.order(created_at: "DESC").paginate(:page => params[:page], :per_page => 4)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @fondo = true
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @fondo = true
  end

  # GET /movies/1/edit
  def edit
    @fondo = true
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :link, :video, :tag, :description, :avatar, :year, :director, :duration , :country, :actors, :category_id)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
end

app/controllers/series_temps_controller.rb
class SeriesTempsController < ApplicationController
  before_action :set_series_temp, only: [:show, :edit, :update, :destroy]

  # GET /series_temps
  # GET /series_temps.json
  def index
      @q = SeriesTemp.ransack(params[:q])
      @series_temps = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 5).order(name: :asc)    
  end

  def buscador
     
      respond_to do |f|
        f.js
      end  
  end

  # GET /series_temps/1
  # GET /series_temps/1.json
  def show
   @capitulos = @series_temp.seasons.paginate(:page => params[:page], :per_page => 1).order(orden: :asc)
  end
  


  # GET /series_temps/new
  def new
    @series_temp = SeriesTemp.new
  end

  # GET /series_temps/1/edit
  def edit
  end

  # POST /series_temps
  # POST /series_temps.json
  def create
    @series_temp = SeriesTemp.new(series_temp_params)

    respond_to do |format|
      if @series_temp.save
        format.html { redirect_to edit_series_temp_url(@series_temp), notice: 'Series temp was successfully created.' }
        format.json { render :show, status: :created, location: @series_temp }
      else
        format.html { render :new }
        format.json { render json: @series_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series_temps/1
  # PATCH/PUT /series_temps/1.json
  def update
    respond_to do |format|
      if @series_temp.update(series_temp_params)
        format.html { redirect_to edit_series_temp_url(@series_temp), notice: 'Series temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @series_temp }
      else
        format.html { render :edit }
        format.json { render json: @series_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series_temps/1
  # DELETE /series_temps/1.json
  def destroy
    @series_temp.destroy
    respond_to do |format|
      format.html { redirect_to series_temps_url, notice: 'Series temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series_temp
      @series_temp = SeriesTemp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_temp_params
      params.require(:series_temp).permit(:name, :link, :video, :tag, :description, :year, :director, :duration, :country,  :baner,:imagen, 
        seasons_attributes: [:id, :name, :link, :video, :tag, :description, :year, :imagen, :orden ,:_destroy , 
        chapters_attributes: [:id, :name,  :link, :description, :duration, :orden, :_destroy] ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buscador_helper.rb
module BuscadorHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/comment_serie_helper.rb
module CommentSerieHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    
    def estrella_pelicula
      mala = Comment.where(movie_id: @movie).rewhere(likes: 0)
      m = mala.count.to_i 
      regular = Comment.where(movie_id: @movie).rewhere(likes: 1) 
      r =regular.count.to_i * 2 
      buena = Comment.where(movie_id: @movie).rewhere(likes: 2) 
      b = buena.count.to_i * 3 
      buenisima = Comment.where(movie_id: @movie).rewhere(likes: 3) 
      bb = buenisima.count.to_i * 4 
      excelente = Comment.where(movie_id: @movie).rewhere(likes: 4) 
      e = excelente.count.to_i * 5 
      m+r+b+bb+e 
        
    end
    
end

app/helpers/seasons_helper.rb
module SeasonsHelper
      

end

app/helpers/series_temps_helper.rb
module SeriesTempsHelper

 
end

app/views/series_temps/_chapter_fields.html.erb
<div class="nested-fields jumbotron">
  
  <div class="">
   <div class="x">
     <div class="col-md-3">
        <div class="field">
    <%= f.label :orden %><br>
    <%= f.number_field :orden, class: 'form-control input-sm' , :required => true%>
  </div>
     </div>
     <div class="col-md-3">
       <%= f.label :link_uploaded %><br>
    <%= f.text_field :link , class: 'form-control input-sm' , :required => true%>
     </div>
     <div class="col-md-3">
      <%= f.label :nombre_cap %><br>
    <%= f.text_field :description, class: 'form-control input-sm' %>  
     </div>
     <div class="col-md-3">
      <%= f.label :descargar %><br>
    <%= f.text_field :duration, class: 'form-control input-sm' %>  
     </div>
   </div>
 </div>
  
 

    
  <%= link_to_remove_association "Descartar Capìtulo", f %>   
  </div>

</div>
  

app/views/series_temps/_form.html.erb
 <% if current_user == User.find(1) %>
    
  <%= form_for(@series_temp) do |f| %>
  <% if @series_temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series_temp.errors.count, "error") %> prohibited this series_temp from being saved:</h2>

      <ul>
      <% @series_temp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name , class: 'form-control input-sm', :required => true %>
        </div>
    </div>
    <div class="col-md-2">
        <div class="field">
          <%= f.label :link %><br>
          <%= f.text_field :link, class: 'form-control input-sm' %>
        </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :video %><br>
        <%= f.text_field :video, class: 'form-control input-sm', :required => true %>
      </div>
  
    </div>


    <div class="col-md-2">
  
        <%= f.label :tag %><br>
        <%= f.text_field :tag , class: 'form-control input-sm' %>
  
    </div>
    <div class="col-md-2">
     
        <%= f.label :description %><br>
        <%= f.text_area :description , class: 'form-control input-sm'%>

    </div>
    <div class="col-md-2">
      

    <%= f.label :year %><br>
    <%= f.text_field :year , class: 'form-control input-sm' %>


  </div>
</div>




  <div class="row">
    <div class="col-md-2">
      <div class="field">
      <%= f.label :director %><br>
      <%= f.text_field :director, class: 'form-control input-sm'%>
    </div>
  
    </div>
    <div class="col-md-2">
       <div class="field">
      <%= f.label :duration %><br>
      <%= f.text_field :duration, class: 'form-control input-sm' %>
    </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :country %><br>
        <%= f.text_field :country, class: 'form-control input-sm' %>
      </div>
    </div>


<div class="col-md-2">
   

    <%= f.label :banner_1280x720px %><br>
    <%= f.text_field :baner, class: 'form-control input-sm' %>  
    </div>
  
  <div class="col-md-2">
        <%= f.label :imagen_logo_mitad_850x80px %>
      <%= f.text_field :imagen, class:'form-control' %>
    </div>



  </div>


<br>







  <div id="season">










    <%= f.fields_for :seasons do |season| %>
     <%= render 'season_fields', f: season %>
    <% end %>     
    <div class="links">
      <%= link_to_add_association 'Agregar Temporada', f, :seasons , 'data-association-insertion-method'    => 'before' %>

    </div>
     
  </div>
  




</div>




<br>





  
  <br>
  

    


  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

     
    <% end %> 

app/views/series_temps/_search.html.erb
<h1>HOLA MUNDO</h1>

app/views/series_temps/_season_fields.html.erb
<div class="nested-fields well back_t">


<table class="table table-hover">
  <thead>
    <tr>
      <th><%= f.label :name %></th>
      <th><%= f.label :link %></th>
      <th><%= f.label :trailer_youtube %></th>
      <th><%= f.label :tag %></th>
      <th><%= f.label :description %></th>
      <th><%= f.label :year %></th>
      <th><%= f.label :duration %></th>
      <th><%= f.label :imagen %></th>
   
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.number_field :orden , class: 'form-control input-sm'%></td>
      <td><%= f.text_field :link , class: 'form-control input-sm'%></td>
      <td><%= f.text_field :video , class: 'form-control input-sm'%></td>
      <td><%= f.text_field :tag , class: 'form-control input-sm'%></td>
      <td><%= f.text_area :description , class: 'form-control input-sm'%></td>
      <td><%= f.text_field :year , class: 'form-control input-sm'%></td>
      <td><%= f.text_field :duration , class: 'form-control input-sm'%></td>
      <td><%= f.text_field :imagen , class: 'form-control input-sm'%></td>

    </tr>
  </tbody>
</table>

        
    
    <div id="chapter">
    
    <%= f.fields_for :chapters do |chapter| %>
     

        <%= render 'chapter_fields', f: chapter %>


    <% end %>     
    <div class="links">
      <%= link_to_add_association 'Agregar Capìtulo', f, :chapters , 'data-association-insertion-method'    => 'before' %>

    </div>
     
  </div>
    
    
   
    <div class="col-md-4 col-md-offset-8"> <%= link_to_remove_association "Descartar Temporada", f %>   </div>
  </div>

</div>
  

app/views/series_temps/buscador.html.erb
<%= render 'series_temps/search' %>

app/views/series_temps/buscador.js.erb
$('#traer').html('<%= j render "/series_temps/search" %>')

app/views/series_temps/edit.html.erb
<h1>Editando Series </h1>

<%= render 'form' %>

<%= link_to 'Show', @series_temp %> |
<%= link_to 'Back', series_temps_path %>

app/views/series_temps/index.html.erb
<p id="notice"><%= notice %></p>


<style type="text/css">
  .carousel{
    background: #2f4357;
    margin-top: 20px;
    
  }
  .carousel .item img{
    margin: 0 auto; /* Align slide image horizontally center */
  }
  .bs-example{
   margin: 20px;
 }
 img{
  height: 500px;
  
}
</style>

<script type="text/javascript">
  $(document).ready(function(){
   $("#myCarousel").carousel();
 });
</script>

<div class="bs-example">
  <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
   <!-- Carousel indicators -->
   <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>   
  <!-- Wrapper for carousel items -->
  <div class="carousel-inner">
    <div class="active item">
      <%= image_tag("banner_1.png", class:'img-responsive') %>
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
     <%= image_tag("logojikan1.jpg", class:'img-responsive') %>
     <div class="carousel-caption">
       
     </div>
   </div>
   <div class="item">
    <%= image_tag("logojikan2.jpg", class:'img-responsive') %>
    <div class="carousel-caption">
     
    </div>
  </div>
  <div class="item">
    <%= image_tag("logojikan3.jpg", class:'img-responsive') %>
    <div class="carousel-caption">
     
    </div>
  </div>
</div>
<!-- Carousel controls -->
<a class="carousel-control left" href="#myCarousel" data-slide="prev">
  <span class="glyphicon glyphicon-chevron-left"></span>
</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">
  <span class="glyphicon glyphicon-chevron-right"></span>
</a>
</div>
</div>




<div class="container">
 
  <!-- Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-6">
       <h1 class="page-header">Series
         <small>Recientes</small>
         
       </h1>

       <%= search_form_for @q do |f| %>
       <div class="row">
        <div class="col-md-6">


          <%= f.search_field  :name_or_tag_or_description_or_year_or_director_or_country_cont , class: 'form-control' %>
        </div>
        <div class="col-md-6">
          <%= f.submit "Buscar", class: 'btn btn-default' %>

        </div>
      </div>

      
      <% end %>
      <%= will_paginate @series_temps, renderer: BootstrapPagination::Rails %>

    </div>
    <div class="col-md-6">
      <% if current_user == User.find(1) %>
      
      <%= link_to image_tag('cinta.png',class:'nuevo'), new_series_temp_path %>
      
      <% end %> 
    </div>
    
  </div>
</div>

<br>
<!-- /.row -->

<!-- Projects Row -->

<% @series_temps.each do |series_temp| %>

<% 
youtube_2 = series_temp.video.split("=").last
youtube_2 =  "https://www.youtube.com/embed/" + youtube_2  
%>

<div class="row">
  <div class="col-md-12 portfolio-item">
   
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <%= link_to  series_temp do %>
        <img src="<%= series_temp.baner %>" class="img-responsive  baja nn">
        
        <% end %>
      </div>
      <div class="col-sm-12 col-md-6">
        <div class="embed-container baja bb">    
         <iframe src="<%= youtube_2 %>" frameborder="0" allowfullscreen></iframe>
       </div> 
     </div>
   </div>
   
   
   <h3><%= link_to  series_temp do %>
    <%= series_temp.name %>
    <% end %>
  </h3>
  
  <p><%= series_temp.description %></p>
  <% if current_user == User.find(1) %>
  <td><%= link_to 'Editar', edit_series_temp_path(series_temp) %></td>
  <td><%= link_to 'Eliminar', series_temp, method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
  
  
  
  <% end %>
  <br></br>
  
  
</div>

</div>
<% end %>  

<!-- /.row -->
<div class="row">
  <div class="col-lg-12">
    <div class="col-md-6">
     
      <%= search_form_for @q do |f| %>
      <div class="row">
        <div class="col-md-6">


          <%= f.search_field  :name_or_tag_or_description_or_year_or_director_or_country_cont , class: 'form-control' %>
        </div>
        <div class="col-md-6">
          <%= f.submit "Buscar", class: 'btn btn-default' %>

        </div>
      </div>

      
      <% end %>
      <%= will_paginate @series_temps, renderer: BootstrapPagination::Rails %>

    </div>
    
    
  </div>
</div>

app/views/series_temps/new.html.erb
<h1>Nueva Serie</h1>

<%= render 'form' %>

<%= link_to 'Back', series_temps_path %>

app/views/series_temps/show.html.erb
  <p id="notice"><%= notice %></p>
<% a = 0 %>
<script>
  $(document).on('page:change', function () {
    

  });
</script>


<div class="foto">
          <img src=" <%= @series_temp.imagen %>">
         
          
       </div>
       <h1 class="titulo"><%= @series_temp.name %></h1> 
    <br> <br>



        <%     youtube =  @series_temp.video.split("=").last
               youtube =  "https://www.youtube.com/embed/" + youtube  
              %>
   
    
<div class="container-fluid">
  <div class="col-lg-6">
    <div class="hidden-xs">
  <dl class="dl-horizontal let">
    <dt>Tag</dt>
    <dd><%= @series_temp.tag %></dd>
    <dt>Año</dt>
    <dd><%= @series_temp.year %></dd>
    <dt>Director</dt>
    <dd><%= @series_temp.director %></dd>
    <dt>Duraciòn</dt>
    <dd><%= @series_temp.duration %></dd>
    <dt>Paìs</dt>
    <dd><%= @series_temp.country %></dd>
    <dt>Descripciòn</dt>
    <dd><%= @series_temp.description %></dd>
  </dl>
</div>

  </div>
  <div class="col-xs-12 col-lg-6">
    <br> <br>
  <div class="descripcion scroll">
  
         
     
     
<div class="container-fluid marge">
  
     <% @series_temp.seasons.order('name DESC').each do |season| %>
     

         <div class="row">
            <div class="col-md-12 portfolio-item_1">
           
              <div class="row">
                <div class="col-sm-12 col-md-6">
                <div class="foto baja">
                  
                  <img src="<%= season.imagen %>" class="img-responsive  baja nn">
                  
<br>
        
                </div>
                
                </div>
                <div class="col-sm-12 col-md-6">
              <% 
                
                 youtube_1 = season.video.split("=").last
                 youtube =  "https://www.youtube.com/embed/" + youtube_1
             
              %>
              <div class="embed-container baja bb">
              <iframe class="" src="<%= youtube %>" frameborder="0" allowfullscreen></iframe>
               </div>


                </div>
               
              </div>
                
             
                  
                  
            <br></br>
            
            
            </div>
           
            </div>  
          
                  
                
            <div class="row">
              <div class="col-xs-12">
                <div class="cuadro">
                  
               <table class="table ">
                  <thead>
                    <tr>
                      <th>Temporada</th>
                     
                      <th>Tags</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><%= season.name %></td>
           
                      <td><%= season.tag %></td>
                    </tr>
                  </tbody>
                 </table> 
                  <h4>Descripciòn</h4>
                  <p>
                   <%= season.description %> 
                  </p>
                
             
                </div>
                
                
              </div>
            </div>  
    <br></br>
     <% end %> 
       
</div>

   

    

     
  
  </div>
</div>

  </div>
  
  
  
  <br>
  
<div class="container">
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Comentarios
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
       
      <div class="">
        <div class="col-md-9">
          
       
          <% @series_temp.comentarios.each do |comment| %>
           

            <blockquote>
            <p><b><%= comment.user %></b></p>
            <p>
              <%= comment.description %>
            </p>
          </blockquote>
          
             <% if current_user == User.find(1) %>
    
          
             <%= link_to 'Destroy Comment', [comment.series_temp, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

              <% end %>
          <% end %>

  

        </div>
        <div class="col-md-3">
          <%= form_for([@series_temp, @series_temp.comentarios.build]) do |f| %>
            <p class="boldd">
              <%= f.label :usuario %><br>
              <%= f.text_field :user , :required => true, class: 'form-control'%>
            </p>
            <p class="boldd">
              <%= f.label :comentario %><br>
              <%= f.text_area :description , :required => true, class: 'form-control'%>
            </p>
            <p>
              <%= f.submit "Agregar comentario", class: 'btn btn-default form-control' %>
            </p>
          <% end %>


  

        </div>
      </div>





       









      </div>
    </div>
  </div>


</div>



</div>
  
  

    
<div class="container-fluid">
  
<hr>

<div class="row">
  <div class="col-md-2">
  <h2 class="text-right">Temporadas</h2>
</div>
<div class="col-md-10">
  <%= will_paginate @capitulos, renderer: BootstrapPagination::Rails %>
</div>

</div>


  
</div>






 
    <div class="container-fluid">
      <section id="pinBoot">
       <% @capitulos.each do |season| %>
       
      <% season.chapters.order('orden DESC').each do |chapter| %>
      
      <article class="white-panel">
        <h2 class="centrar">Temporada <%= chapter.season.orden %></h2>
        <h4 class="centrar">Capítulo <%= chapter.orden %><a target="_blank" href="<%= chapter.duration %>"> Descargar</a></h4>
       <p class="centrar">
          <%= chapter.description  %>
   
              
        </p>


        
      

              <div class="embed-container">
                <iframe class="" src="<%= chapter.link %>" frameborder="0" allowfullscreen></iframe>

              </div>
        




        
      </article>
     
      <% end %>
     

      <% end %>

    </section>
<div class="row">
  <div class="col-md-2">
  <h2 class="text-right">Temporadas</h2>
</div>
<div class="col-md-10">
  <%= will_paginate @capitulos, renderer: BootstrapPagination::Rails %>
</div>

</div>

    </div>







<div class="container">
   <% if current_user == User.find(1) %>
    
   <%= link_to 'Edit', edit_series_temp_path(@series_temp) %> |
  <%= link_to 'Back', series_temps_path %>
     
    <% end %> 



</div>

<%= link_to 'traer', buscador_index_path, remote: true %>

 <div id="traer"></div>