config/routes.rb
Rails.application.routes.draw do
  
  get 'buscador/index'

  resources :series_temps do
    resources :comentarios
  end
 
  devise_for :users
  resources :categories
  resources :movies do
  resources :comments  
  end  

    root 'series_temps#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :movies
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :season

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :series_temp
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :movie
 
  enum likes: {mala: 0, regular: 1, buena: 2, buenisima: 3 , excelente: 4}
end

app/models/comment_serie.rb
class CommentSerie < ActiveRecord::Base
  belongs_to :series_temp
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many  :comments, dependent: :destroy
  belongs_to :category
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
  before_validation :youtube
   
  def youtube   #este sirve para cambiar el link que se agrega desde youtube, por el embed
    youtube = video.split("=").last   
    self.video = "https://www.youtube.com/embed/" + youtube
  end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :series_temp
  has_many :chapters, dependent: :destroy
  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true

end

app/models/series_temp.rb
class SeriesTemp < ActiveRecord::Base
  has_many :seasons, dependent: :destroy
  accepts_nested_attributes_for :seasons, reject_if: :all_blank, allow_destroy: true
  has_many :comentarios, dependent: :destroy    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.order(created_at: "DESC").paginate(:page => params[:page], :per_page => 4)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @fondo = true
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @fondo = true
  end

  # GET /movies/1/edit
  def edit
    @fondo = true
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :link, :video, :tag, :description, :avatar, :year, :director, :duration , :country, :actors, :category_id)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buscador_helper.rb
module BuscadorHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/comment_serie_helper.rb
module CommentSerieHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    
    def estrella_pelicula
      mala = Comment.where(movie_id: @movie).rewhere(likes: 0)
      m = mala.count.to_i 
      regular = Comment.where(movie_id: @movie).rewhere(likes: 1) 
      r =regular.count.to_i * 2 
      buena = Comment.where(movie_id: @movie).rewhere(likes: 2) 
      b = buena.count.to_i * 3 
      buenisima = Comment.where(movie_id: @movie).rewhere(likes: 3) 
      bb = buenisima.count.to_i * 4 
      excelente = Comment.where(movie_id: @movie).rewhere(likes: 4) 
      e = excelente.count.to_i * 5 
      m+r+b+bb+e 
        
    end
    
end

app/helpers/seasons_helper.rb
module SeasonsHelper
      

end

app/helpers/series_temps_helper.rb
module SeriesTempsHelper

 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jikanseries</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
</head>
<% if @fondo == true %>
<body class="fondoform " data-no-turbolink="true">
<% else %>
<body class="fondo" data-no-turbolink="true">
<% end %>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   <%= link_to image_tag('logojikan.png',class:'logo'), root_path, class:'navbar-brand' %>
                    
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                     <li><%= link_to 'Peliculas', movies_path %></li>   
                       <li><%= link_to 'Series', series_temps_path %> </li>
                        
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>